default_install_hook_types: [ pre-commit, post-merge, post-rewrite ]
exclude: .*.md
repos:
  - repo: local
    hooks:
      - id: golangci-lint
        name: golangci-lint
        description: Fast linters runner for Go. Note that only modified files are linted, so linters like 'unused' that need to scan all files won't work as expected.
        entry: ./hooks/lint-server-files.sh
        language: golang
        types: [ go ]
        require_serial: true
        pass_filenames: false
      - id: format-frontend-files
        name: format frontend files
        entry: ./hooks/format-frontend-files.sh
        language: system
        types: [ javascript, html, ts, vue ]
      - id: lint-frontend-files
        name: lint frontend files
        entry: ./hooks/lint-frontend-files.sh
        language: system
        types: [ javascript, html, ts, vue ]
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.5.0
    hooks:
      - id: end-of-file-fixer
      - id: forbid-submodules
      - id: trailing-whitespace
      - id: mixed-line-ending
        args: [ '--fix=lf' ]
