default_install_hook_types: [ pre-commit, post-merge, post-rewrite ]
exclude: .*.md
repos:
  - repo: local
    hooks:
      - id: lint-server-files
        name: lint server files
        entry: .hooks/lint-server-files.sh
        language: system
        types: [ go ]
      - id: lint-frontend-files
        name: lint frontend files
        entry: .hooks/lint-frontend-files.sh
        language: system
        types: [ javascript, html, ts, vue ]
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.5.0
    hooks:
      - id: end-of-file-fixer
      - id: forbid-submodules
      - id: trailing-whitespace
      - id: mixed-line-ending
        args: [ '--fix=lf' ]
