version: '3'

services:
  blazegraph:
    image: conjecto/blazegraph:2.1.5
    restart: always
    environment:
      JAVA_OPTS: "-Xms1g -Xmx4g"
    volumes:
      - ./database/dataset:/docker-entrypoint-initdb.d
  datatourisme:
    build: database
    restart: always
    ports:
      - 8081:80
    depends_on:
      - blazegraph
