// Code generated by github.com/Khan/genqlient, DO NOT EDIT.

package graphql

import (
	"context"

	"github.com/Khan/genqlient/graphql"
)

// GetTotalPoiPointOfInterest_ResultSet includes the requested fields of the GraphQL type PointOfInterest_ResultSet.
type GetTotalPoiPointOfInterest_ResultSet struct {
	Total int `json:"total"`
}

// GetTotal returns GetTotalPoiPointOfInterest_ResultSet.Total, and is useful for accessing the field via an interface.
func (v *GetTotalPoiPointOfInterest_ResultSet) GetTotal() int { return v.Total }

// GetTotalResponse is returned by GetTotal on success.
type GetTotalResponse struct {
	Poi GetTotalPoiPointOfInterest_ResultSet `json:"poi"`
}

// GetPoi returns GetTotalResponse.Poi, and is useful for accessing the field via an interface.
func (v *GetTotalResponse) GetPoi() GetTotalPoiPointOfInterest_ResultSet { return v.Poi }

// The query or mutation executed by GetTotal.
const GetTotal_Operation = `
query GetTotal {
	poi {
		total
	}
}
`

func GetTotal(
	ctx_ context.Context,
	client_ graphql.Client,
) (*GetTotalResponse, error) {
	req_ := &graphql.Request{
		OpName: "GetTotal",
		Query:  GetTotal_Operation,
	}
	var err_ error

	var data_ GetTotalResponse
	resp_ := &graphql.Response{Data: &data_}

	err_ = client_.MakeRequest(
		ctx_,
		req_,
		resp_,
	)

	return &data_, err_
}
