definitions:
  graphql.Error:
    properties:
      error:
        example: string
        type: string
    type: object
  graphql.GetDrinksPoiPointOfInterest_ResultSet:
    properties:
      results:
        items:
          $ref: '#/definitions/graphql.GetDrinksPoiPointOfInterest_ResultSetResultsPointOfInterest'
        type: array
      total:
        type: integer
    type: object
  graphql.GetDrinksPoiPointOfInterest_ResultSetResultsPointOfInterest:
    properties:
      hasContact:
        description: L&#039;agent à contacter pour affaires générales relatives à
          ce POI.
        items:
          $ref: '#/definitions/graphql.GetDrinksPoiPointOfInterest_ResultSetResultsPointOfInterestHasContactAgent'
        type: array
      rdfs_comment:
        description: Description de la ressource.
        items:
          $ref: '#/definitions/graphql.GetDrinksPoiPointOfInterest_ResultSetResultsPointOfInterestRdfs_commentLangString'
        type: array
      rdfs_label:
        description: Etiquette courte décrivant la ressource.
        items:
          $ref: '#/definitions/graphql.GetDrinksPoiPointOfInterest_ResultSetResultsPointOfInterestRdfs_labelLangString'
        type: array
    type: object
  graphql.GetDrinksPoiPointOfInterest_ResultSetResultsPointOfInterestHasContactAgent:
    properties:
      foaf_homepage:
        description: L&#039;adresse du site internet d&#039;un Agent.
        items:
          type: string
        type: array
      schema_email:
        description: Un courriel, courrier électronique.
        items:
          type: string
        type: array
      schema_telephone:
        description: Un numéro de téléphone.
        items:
          type: string
        type: array
    type: object
  graphql.GetDrinksPoiPointOfInterest_ResultSetResultsPointOfInterestRdfs_commentLangString:
    properties:
      value:
        description: Literal value
        type: string
    type: object
  graphql.GetDrinksPoiPointOfInterest_ResultSetResultsPointOfInterestRdfs_labelLangString:
    properties:
      value:
        description: Literal value
        type: string
    type: object
  graphql.GetDrinksResponse:
    properties:
      poi:
        $ref: '#/definitions/graphql.GetDrinksPoiPointOfInterest_ResultSet'
    type: object
  graphql.GetEnjoyPoiPointOfInterest_ResultSet:
    properties:
      results:
        items:
          $ref: '#/definitions/graphql.GetEnjoyPoiPointOfInterest_ResultSetResultsPointOfInterest'
        type: array
      total:
        type: integer
    type: object
  graphql.GetEnjoyPoiPointOfInterest_ResultSetResultsPointOfInterest:
    properties:
      rdfs_comment:
        description: Description de la ressource.
        items:
          $ref: '#/definitions/graphql.GetEnjoyPoiPointOfInterest_ResultSetResultsPointOfInterestRdfs_commentLangString'
        type: array
      rdfs_label:
        description: Etiquette courte décrivant la ressource.
        items:
          $ref: '#/definitions/graphql.GetEnjoyPoiPointOfInterest_ResultSetResultsPointOfInterestRdfs_labelLangString'
        type: array
    type: object
  graphql.GetEnjoyPoiPointOfInterest_ResultSetResultsPointOfInterestRdfs_commentLangString:
    properties:
      value:
        description: Literal value
        type: string
    type: object
  graphql.GetEnjoyPoiPointOfInterest_ResultSetResultsPointOfInterestRdfs_labelLangString:
    properties:
      value:
        description: Literal value
        type: string
    type: object
  graphql.GetEnjoyResponse:
    properties:
      poi:
        $ref: '#/definitions/graphql.GetEnjoyPoiPointOfInterest_ResultSet'
    type: object
  graphql.GetTotalPoiPointOfInterest_ResultSet:
    properties:
      total:
        type: integer
    type: object
  graphql.GetTotalResponse:
    properties:
      poi:
        $ref: '#/definitions/graphql.GetTotalPoiPointOfInterest_ResultSet'
    type: object
externalDocs:
  description: OpenAPI
  url: https://swagger.io/resources/open-api/
info:
  contact:
    email: support@swagger.io
    name: API Support
    url: http://www.swagger.io/support
  description: This is the API of the Idee project!
  license:
    name: Apache 2.0
    url: http://www.apache.org/licenses/LICENSE-2.0.html
  termsOfService: http://swagger.io/terms/
  title: Idee API
  version: "1.0"
paths:
  /drink:
    get:
      consumes:
      - application/json
      description: Get available drinks (bars, bistros) in a city
      parameters:
      - example: Paris
        in: query
        name: city
        required: true
        type: string
      - example: 1
        in: query
        minimum: 1
        name: page
        required: true
        type: integer
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/graphql.GetDrinksResponse'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/graphql.Error'
      summary: Total
      tags:
      - graphql
  /enjoy:
    get:
      consumes:
      - application/json
      description: Get events|activities from our DATATourisme API
      parameters:
      - in: query
        name: city
        required: true
        type: string
      - in: query
        minimum: 0
        name: page
        required: true
        type: integer
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/graphql.GetEnjoyResponse'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/graphql.Error'
      summary: Enjoy
      tags:
      - graphql
  /total:
    get:
      consumes:
      - application/json
      description: Get total number of objets in database
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/graphql.GetTotalResponse'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/graphql.Error'
      summary: Total
      tags:
      - graphql
securityDefinitions:
  BasicAuth:
    type: basic
swagger: "2.0"
