definitions:
  graphql.GetTotalPoiPointOfInterest_ResultSet:
    properties:
      total:
        type: integer
    type: object
  graphql.GetTotalResponse:
    properties:
      poi:
        $ref: '#/definitions/graphql.GetTotalPoiPointOfInterest_ResultSet'
    type: object
  main.Response:
    properties:
      message:
        example: pong
        type: string
    type: object
externalDocs:
  description: OpenAPI
  url: https://swagger.io/resources/open-api/
info:
  contact:
    email: support@swagger.io
    name: API Support
    url: http://www.swagger.io/support
  description: This is the API of the Idee project!
  license:
    name: Apache 2.0
    url: http://www.apache.org/licenses/LICENSE-2.0.html
  termsOfService: http://swagger.io/terms/
  title: Idee API
  version: "1.0"
paths:
  /ping:
    get:
      consumes:
      - application/json
      description: Ping the server
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/main.Response'
        "400":
          description: Bad Request
          schema:
            type: string
        "404":
          description: Not Found
          schema:
            type: string
        "500":
          description: Internal Server Error
          schema:
            type: string
      summary: Ping
      tags:
      - ping
  /total:
    get:
      consumes:
      - application/json
      description: Get total number of objets in database
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/graphql.GetTotalResponse'
        "500":
          description: Internal Server Error
          schema:
            type: string
      summary: Total
      tags:
      - graphql
securityDefinitions:
  BasicAuth:
    type: basic
swagger: "2.0"
