name: server
on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
    paths:
      - 'server/**'

jobs:
  server:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: server
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-go@v5
      - uses: yegorrybchenko/go-swag-action@v0.1
        with:
          command: init -d server 
          equalToGoPath: docs/docs.go
          equalToGoOriginPath: server/docs/docs.go
          swagWersion: 1.8.11
      - name: format code
        run: | 
          go fmt
          git diff --exit-code
      - name: golangci-lint
        uses: golangci/golangci-lint-action@v4
        with:
          version: v1.54
          working-directory: server
      - uses: n8maninger/action-golang-test@v1
        with:
          args: "-race;-failfast;-tags=testing debug netgo;-cover"
          working-directory: server

