name: server
on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
    paths:
      - 'server/**'

jobs:
  server:
    runs-on: ubuntu-latest
    permissions:
      # Required: allow read access to the content for analysis.
      contents: read
      # Optional: allow read access to pull request. Use with `only-new-issues` option.
      pull-requests: read
      # Optional: Allow write access to checks to allow the action to annotate code in the PR.
      checks: write
    defaults:
      run:
        working-directory: server
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-go@v5
      - name: format code
        run: go fmt
        working-directory: ./server
      - uses: yegorrybchenko/go-swag-action@v0.1
        with:
          command: init -d server
          swagWersion: 1.8.11
      - name: golangci-lint
        uses: golangci/golangci-lint-action@v4
        with:
          version: v1.54
          working-directory: server
      - uses: n8maninger/action-golang-test@v1
        with:
          args: "-race;-failfast;-tags=testing debug netgo;-cover"
          working-directory: ./server

