name: server
on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
    paths:
      - 'server/**'

jobs:
  server:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: server
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-go@v5
      - name: moove to server dir
        run: cd ./server
      - name: format code
        run: go fmt
      - uses: yegorrybchenko/go-swag-action@v0.1
        with:
          command: init && fmt
          swagWersion: 1.8.12
      - name: golangci-lint
        uses: golangci/golangci-lint-action@v4
      - uses: n8maninger/action-golang-test@v1
        with:
          args: "-race;-failfast;-tags=testing debug netgo;-cover"

