name: server
on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
    paths:
      - 'server/**'

jobs:
  server:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: server
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-go@v5
      - name: format code
        run: go fmt
      - name: download swag
        run: go get -u github.com/swaggo/swag/cmd/swag
      - name: init swagger comment
        run:  swag init
        working-directory: ./server
      - name: format swagger comment
        run:  swag fmt
        working-directory: ./server
      - name: golangci-lint
        uses: golangci/golangci-lint-action@v4
      - name: run test
        run: go test -v
      - name: runt test coverage
        run: go test -cover


